name = "OrgMode"
uuid = "efd43031-27bf-443e-b336-0688ecb9ff2a"
authors = ["Tim Quelch <tim@tquelch.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
AbstractTrees = "0.3"
Lazy = "0.14, 0.15"
julia = "1.4"
