name = "OrgMode"
uuid = "efd43031-27bf-443e-b336-0688ecb9ff2a"
authors = ["Tim Quelch <tim@tquelch.com> and contributors"]
version = "0.1.0"

[deps]
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
Lazy = "0.15"
julia = "1.4"
